### ISSUE TITLE
AC3.3 Geotagging with MP may not work

### ISSUE THREAD

**Issue by rmackay9** [diydrones/MissionPlanner#946]
See reports on the AC3.3-beta testing thread from Glenn M and Shaun Bell.

http://diydrones.com/forum/topics/copter-3-3-beta-testing?commentId=705844%3AComment%3A2057273&xg_source=msg_com_forum

**Comment by taedla01** [comment]
Hello @rmackay9,

This mistake is due to the inclusion of the variable "Timeus" to CAM messages and restructuring of the message CAM data. Note that the variable "Timeus" has been included in all messages, so the messages ATT and GPS are also affected. To fix this, simply adjust properly "offtsets" in the setup screen Geotag Mission Planner tool.

The following configuration is incorrect (taken from the conversation on DIYDrones):
 
![georef](https://cloud.githubusercontent.com/assets/3317796/9109210/27aee222-3c34-11e5-9416-1c04fdacfe21.jpg)

With new releases, for ArduCopter, Mission Planner must be set like this:

![georef corrected](https://cloud.githubusercontent.com/assets/3317796/9109300/f9ac5b2e-3c34-11e5-8b32-cfef501cb1a3.jpg)

**Comment by meee1** [comment]
thanks taedla01, ive updated the default to what you have said.

**Comment by taedla01** [comment]
Wooww! Very fast response @meee1!  ;)
I forgot to mention:

Tested with Mission Planner 1.3.30 and current master branch of ArduCopter (AC RC8+)

Thanks Michael,
Regards from Spain,
Dario.
